athletes_list = [
    {'Country_Code': 'USA', 'Country': 'United States', 'Female': 328, 'Male': 291, 'Total Athletes': 619},
    {'Country_Code': 'FRA', 'Country': 'France', 'Female': 295, 'Male': 305, 'Total Athletes': 600},
    {'Country_Code': 'AUS', 'Country': 'Australia', 'Female': 265, 'Male': 210, 'Total Athletes': 475},
    {'Country_Code': 'GER', 'Country': 'Germany', 'Female': 225, 'Male': 232, 'Total Athletes': 457},
    {'Country_Code': 'JPN', 'Country': 'Japan', 'Female': 201, 'Male': 230, 'Total Athletes': 431},
    {'Country_Code': 'ESP', 'Country': 'Spain', 'Female': 202, 'Male': 199, 'Total Athletes': 401},
    {'Country_Code': 'CHN', 'Country': 'China', 'Female': 264, 'Male': 134, 'Total Athletes': 398},
    {'Country_Code': 'ITA', 'Country': 'Italy', 'Female': 192, 'Male': 205, 'Total Athletes': 397},
    {'Country_Code': 'GBR', 'Country': 'Great Britain', 'Female': 178, 'Male': 164, 'Total Athletes': 342},
    {'Country_Code': 'CAN', 'Country': 'Canada', 'Female': 203, 'Male': 129, 'Total Athletes': 332},
    {'Country_Code': 'BRA', 'Country': 'Brazil', 'Female': 164, 'Male': 126, 'Total Athletes': 290},
    {'Country_Code': 'NED', 'Country': 'Netherlands', 'Female': 172, 'Male': 117, 'Total Athletes': 289},
    {'Country_Code': 'POL', 'Country': 'Poland', 'Female': 124, 'Male': 102, 'Total Athletes': 226},
    {'Country_Code': 'NZL', 'Country': 'New Zealand', 'Female': 101, 'Male': 107, 'Total Athletes': 208},
    {'Country_Code': 'HUN', 'Country': 'Hungary', 'Female': 85, 'Male': 92, 'Total Athletes': 177},
    {'Country_Code': 'BEL', 'Country': 'Belgium', 'Female': 88, 'Male': 89, 'Total Athletes': 177},
    {'Country_Code': 'EGY', 'Country': 'Egypt', 'Female': 54, 'Male': 103, 'Total Athletes': 157},
    {'Country_Code': 'KOR', 'Country': 'Korea', 'Female': 81, 'Male': 66, 'Total Athletes': 147},
    {'Country_Code': 'IRL', 'Country': 'Ireland', 'Female': 69, 'Male': 74, 'Total Athletes': 143},
    {'Country_Code': 'ARG', 'Country': 'Argentina', 'Female': 33, 'Male': 110, 'Total Athletes': 143},
    {'Country_Code': 'RSA', 'Country': 'South Africa', 'Female': 63, 'Male': 78, 'Total Athletes': 141},
    {'Country_Code': 'UKR', 'Country': 'Ukraine', 'Female': 69, 'Male': 72, 'Total Athletes': 141},
    {'Country_Code': 'SUI', 'Country': 'Switzerland', 'Female': 66, 'Male': 71, 'Total Athletes': 137},
    {'Country_Code': 'DEN', 'Country': 'Denmark', 'Female': 74, 'Male': 57, 'Total Athletes': 131},
    {'Country_Code': 'SWE', 'Country': 'Sweden', 'Female': 66, 'Male': 59, 'Total Athletes': 125},
    {'Country_Code': 'SRB', 'Country': 'Serbia', 'Female': 44, 'Male': 70, 'Total Athletes': 114},
    {'Country_Code': 'IND', 'Country': 'India', 'Female': 46, 'Male': 66, 'Total Athletes': 112},
    {'Country_Code': 'CZE', 'Country': 'Czechia', 'Female': 49, 'Male': 62, 'Total Athletes': 111},
    {'Country_Code': 'NOR', 'Country': 'Norway', 'Female': 53, 'Male': 56, 'Total Athletes': 109},
    {'Country_Code': 'MEX', 'Country': 'Mexico', 'Female': 63, 'Male': 45, 'Total Athletes': 108},
    {'Country_Code': 'TUR', 'Country': 'Türkiye', 'Female': 54, 'Male': 47, 'Total Athletes': 101},
    {'Country_Code': 'GRE', 'Country': 'Greece', 'Female': 41, 'Male': 59, 'Total Athletes': 100},
    {'Country_Code': 'ROU', 'Country': 'Romania', 'Female': 47, 'Male': 49, 'Total Athletes': 96},
    {'Country_Code': 'SLO', 'Country': 'Slovenia', 'Female': 47, 'Male': 48, 'Total Athletes': 95},
    {'Country_Code': 'ISR', 'Country': 'Israel', 'Female': 33, 'Male': 56, 'Total Athletes': 89},
    {'Country_Code': 'COL', 'Country': 'Colombia', 'Female': 51, 'Male': 37, 'Total Athletes': 88},
    {'Country_Code': 'UZB', 'Country': 'Uzbekistan', 'Female': 31, 'Male': 57, 'Total Athletes': 88},
    {'Country_Code': 'NGR', 'Country': 'Nigeria', 'Female': 63, 'Male': 23, 'Total Athletes': 86},
    {'Country_Code': 'AUT', 'Country': 'Austria', 'Female': 37, 'Male': 47, 'Total Athletes': 84},
    {'Country_Code': 'KAZ', 'Country': 'Kazakhstan', 'Female': 25, 'Male': 54, 'Total Athletes': 79},
    {'Country_Code': 'POR', 'Country': 'Portugal', 'Female': 37, 'Male': 38, 'Total Athletes': 75},
    {'Country_Code': 'KEN', 'Country': 'Kenya', 'Female': 34, 'Male': 40, 'Total Athletes': 74},
    {'Country_Code': 'CRO', 'Country': 'Croatia', 'Female': 15, 'Male': 58, 'Total Athletes': 73},
    {'Country_Code': 'JAM', 'Country': 'Jamaica', 'Female': 32, 'Male': 33, 'Total Athletes': 65},
    {'Country_Code': 'MAR', 'Country': 'Morocco', 'Female': 18, 'Male': 43, 'Total Athletes': 61},
    {'Country_Code': 'CUB', 'Country': 'Cuba', 'Female': 27, 'Male': 34, 'Total Athletes': 61},
    {'Country_Code': 'TPE', 'Country': 'Chinese Taipei', 'Female': 34, 'Male': 26, 'Total Athletes': 60},
    {'Country_Code': 'DOM', 'Country': 'Dominican Republic', 'Female': 25, 'Male': 34, 'Total Athletes': 59},
    {'Country_Code': 'FIN', 'Country': 'Finland', 'Female': 34, 'Male': 23, 'Total Athletes': 57},
    {'Country_Code': 'THA', 'Country': 'Thailand', 'Female': 28, 'Male': 24, 'Total Athletes': 52},
    {'Country_Code': 'LTU', 'Country': 'Lithuania', 'Female': 24, 'Male': 27, 'Total Athletes': 51},
    {'Country_Code': 'PUR', 'Country': 'Puerto Rico', 'Female': 24, 'Male': 27, 'Total Athletes': 51},
    {'Country_Code': 'AZE', 'Country': 'Azerbaijan', 'Female': 20, 'Male': 28, 'Total Athletes': 48},
    {'Country_Code': 'CHI', 'Country': 'Chile', 'Female': 18, 'Male': 30, 'Total Athletes': 48},
    {'Country_Code': 'BUL', 'Country': 'Bulgaria', 'Female': 25, 'Male': 21, 'Total Athletes': 46},
    {'Country_Code': 'ALG', 'Country': 'Algeria', 'Female': 19, 'Male': 27, 'Total Athletes': 46},
    {'Country_Code': 'IRI', 'Country': 'IR Iran', 'Female': 11, 'Male': 30, 'Total Athletes': 41},
    {'Country_Code': 'NGR', 'Country': 'Nigeria', 'Female': 63, 'Male': 23, 'Total athletes': 86},
    {'Country_Code': 'AUT', 'Country': 'Austria', 'Female': 37, 'Male': 47, 'Total athletes': 84},
    {'Country_Code': 'KAZ', 'Country': 'Kazakhstan', 'Female': 25, 'Male': 54, 'Total athletes': 79},
    {'Country_Code': 'POR', 'Country': 'Portugal', 'Female': 37, 'Male': 38, 'Total athletes': 75},
    {'Country_Code': 'KEN', 'Country': 'Kenya', 'Female': 34, 'Male': 40, 'Total athletes': 74},
    {'Country_Code': 'CRO', 'Country': 'Croatia', 'Female': 15, 'Male': 58, 'Total athletes': 73},
    {'Country_Code': 'JAM', 'Country': 'Jamaica', 'Female': 32, 'Male': 33, 'Total athletes': 65},
    {'Country_Code': 'MAR', 'Country': 'Morocco', 'Female': 18, 'Male': 43, 'Total athletes': 61},
    {'Country_Code': 'CUB', 'Country': 'Cuba', 'Female': 27, 'Male': 34, 'Total athletes': 61},
    {'Country_Code': 'TPE', 'Country': 'Chinese Taipei', 'Female': 34, 'Male': 26, 'Total athletes': 60},
    {'Country_Code': 'DOM', 'Country': 'Dominican Republic', 'Female': 25, 'Male': 34, 'Total athletes': 59},
    {'Country_Code': 'FIN', 'Country': 'Finland', 'Female': 34, 'Male': 23, 'Total athletes': 57},
    {'Country_Code': 'THA', 'Country': 'Thailand', 'Female': 28, 'Male': 24, 'Total athletes': 52},
    {'Country_Code': 'LTU', 'Country': 'Lithuania', 'Female': 24, 'Male': 27, 'Total athletes': 51},
    {'Country_Code': 'PUR', 'Country': 'Puerto Rico', 'Female': 24, 'Male': 27, 'Total athletes': 51},
    {'Country_Code': 'AZE', 'Country': 'Azerbaijan', 'Female': 20, 'Male': 28, 'Total athletes': 48},
    {'Country_Code': 'CHI', 'Country': 'Chile', 'Female': 18, 'Male': 30, 'Total athletes': 48},
    {'Country_Code': 'BUL', 'Country': 'Bulgaria', 'Female': 25, 'Male': 21, 'Total athletes': 46},
    {'Country_Code': 'ALG', 'Country': 'Algeria', 'Female': 19, 'Male': 27, 'Total athletes': 46},
    {'Country_Code': 'IRI', 'Country': 'IR Iran', 'Female': 11, 'Male': 30, 'Total athletes': 41},
    {'Country_Code': 'ECU', 'Country': 'Ecuador', 'Female': 24, 'Male': 16, 'Total athletes': 40},
    {'Country_Code': 'EOR', 'Country': 'EOR', 'Female': 13, 'Male': 24, 'Total athletes': 37},
    {'Country_Code': 'FIJ', 'Country': 'Fiji', 'Female': 17, 'Male': 19, 'Total athletes': 36},
    {'Country_Code': 'HKG', 'Country': 'Hong Kong, China', 'Female': 18, 'Male': 16, 'Total athletes': 34},
    {'Country_Code': 'ETH', 'Country': 'Ethiopia', 'Female': 17, 'Male': 16, 'Total athletes': 33},
    {'Country_Code': 'AIN', 'Country': 'AIN', 'Female': 17, 'Male': 15, 'Total athletes': 32},
    {'Country_Code': 'MGL', 'Country': 'Mongolia', 'Female': 18, 'Male': 14, 'Total athletes': 32},
    {'Country_Code': 'ZAM', 'Country': 'Zambia', 'Female': 22, 'Male': 9, 'Total athletes': 31},
    {'Country_Code': 'VEN', 'Country': 'Venezuela', 'Female': 14, 'Male': 17, 'Total athletes': 31},
    {'Country_Code': 'PAR', 'Country': 'Paraguay', 'Female': 6, 'Male': 23, 'Total athletes': 29},
    {'Country_Code': 'INA', 'Country': 'Indonesia', 'Female': 13, 'Male': 16, 'Total athletes': 29},
    {'Country_Code': 'LAT', 'Country': 'Latvia', 'Female': 13, 'Male': 16, 'Total athletes': 29},
    {'Country_Code': 'SVK', 'Country': 'Slovakia', 'Female': 14, 'Male': 14, 'Total athletes': 28},
    {'Country_Code': 'GEO', 'Country': 'Georgia', 'Female': 7, 'Male': 21, 'Total athletes': 28},
    {'Country_Code': 'URU', 'Country': 'Uruguay', 'Female': 4, 'Male': 23, 'Total athletes': 27},
    {'Country_Code': 'MAS', 'Country': 'Malaysia', 'Female': 13, 'Male': 13, 'Total athletes': 26},
    {'Country_Code': 'TUN', 'Country': 'Tunisia', 'Female': 14, 'Male': 12, 'Total athletes': 26},
    {'Country_Code': 'PER', 'Country': 'Peru', 'Female': 17, 'Male': 9, 'Total athletes': 26},
    {'Country_Code': 'MDA', 'Country': 'Republic of Moldova', 'Female': 12, 'Male': 14, 'Total athletes': 26},
    {'Country_Code': 'GUI', 'Country': 'Guinea', 'Female': 5, 'Male': 20, 'Total athletes': 25},
    {'Country_Code': 'UGA', 'Country': 'Uganda', 'Female': 13, 'Male': 12, 'Total athletes': 25},
    {'Country_Code': 'ANG', 'Country': 'Angola', 'Female': 17, 'Male': 8, 'Total athletes': 25},
    {'Country_Code': 'SAM', 'Country': 'Samoa', 'Female': 4, 'Male': 20, 'Total athletes': 24},
    {'Country_Code': 'MLI', 'Country': 'Mali', 'Female': 2, 'Male': 22, 'Total athletes': 24},
    {'Country_Code': 'EST', 'Country': 'Estonia', 'Female': 8, 'Male': 16, 'Total athletes': 24},
    {'Country_Code': 'SGP', 'Country': 'Singapore', 'Female': 16, 'Male': 7, 'Total athletes': 23},
    {'Country_Code': 'IRQ', 'Country': 'Iraq', 'Female': 0, 'Male': 23, 'Total athletes': 23},
    {'Country_Code': 'PHI', 'Country': 'Philippines', 'Female': 15, 'Male': 7, 'Total athletes': 22},
    {'Country_Code': 'BAH', 'Country': 'Bahamas', 'Female': 8, 'Male': 11, 'Total athletes': 19},
    {'Country_Code': 'MNE', 'Country': 'Montenegro', 'Female': 3, 'Male': 16, 'Total athletes': 19},
    {'Country_Code': 'TTO', 'Country': 'Trinidad and Tobago', 'Female': 7, 'Male': 10, 'Total athletes': 17},
    {'Country_Code': 'VIE', 'Country': 'Vietnam', 'Female': 12, 'Male': 4, 'Total athletes': 16},
    {'Country_Code': 'KGZ', 'Country': 'Kyrgyzstan', 'Female': 5, 'Male': 11, 'Total athletes': 16},
    {'Country_Code': 'GUA', 'Country': 'Guatemala', 'Female': 6, 'Male': 10, 'Total athletes': 16},
    {'Country_Code': 'CYP', 'Country': 'Cyprus', 'Female': 9, 'Male': 6, 'Total athletes': 15},
    {'Country_Code': 'ARM', 'Country': 'Armenia', 'Female': 2, 'Male': 13, 'Total athletes': 15},
    {'Country_Code': 'BOT', 'Country': 'Botswana', 'Female': 2, 'Male': 12, 'Total athletes': 14},
    {'Country_Code': 'PRK', 'Country': 'DPR Korea', 'Female': 10, 'Male': 4, 'Total athletes': 14},
    {'Country_Code': 'SRI', 'Country': 'Sri Lanka', 'Female': 9, 'Male': 5, 'Total athletes': 14},
    {'Country_Code': 'NAM', 'Country': 'Namibia', 'Female': 3, 'Male': 11, 'Total athletes': 14},
    {'Country_Code': 'CIV', 'Country': 'Côte d’Ivoire', 'Female': 7, 'Male': 6, 'Total athletes': 13},
    {'Country_Code': 'BIH', 'Country': 'Bosnia and Herzegovina', 'Female': 4, 'Male': 8, 'Total athletes': 12},
    {'Country_Code': 'SEN', 'Country': 'Senegal', 'Female': 2, 'Male': 10, 'Total athletes': 12},
    {'Country_Code': 'HON', 'Country': 'Honduras', 'Female': 4, 'Male': 8, 'Total athletes': 12},
    {'Country_Code': 'SYR', 'Country': 'Syrian Arab Republic', 'Female': 5, 'Male': 6, 'Total athletes': 11},
    {'Country_Code': 'BAR', 'Country': 'Barbados', 'Female': 5, 'Male': 6, 'Total athletes': 11},
    {'Country_Code': 'QAT', 'Country': 'Qatar', 'Female': 4, 'Male': 7, 'Total athletes': 11},
    {'Country_Code': 'SUD', 'Country': 'Sudan', 'Female': 5, 'Male': 5, 'Total athletes': 10},
    {'Country_Code': 'KOS', 'Country': 'Kosovo', 'Female': 4, 'Male': 5, 'Total athletes': 9},
    {'Country_Code': 'MRI', 'Country': 'Mauritius', 'Female': 3, 'Male': 6, 'Total athletes': 9},
    {'Country_Code': 'SUR', 'Country': 'Suriname', 'Female': 2, 'Male': 6, 'Total athletes': 8},
    {'Country_Code': 'LBN', 'Country': 'Lebanon', 'Female': 3, 'Male': 4, 'Total athletes': 7},
    {'Country_Code': 'TJK', 'Country': 'Tajikistan', 'Female': 2, 'Male': 5, 'Total athletes': 7},
    {'Country_Code': 'TOG', 'Country': 'Togo', 'Female': 3, 'Male': 4, 'Total athletes': 7},
    {'Country_Code': 'CPV', 'Country': 'Cabo Verde', 'Female': 3, 'Male': 4, 'Total athletes': 7},
    {'Country_Code': 'NEP', 'Country': 'Nepal', 'Female': 5, 'Male': 2, 'Total athletes': 7},
    {'Country_Code': 'SOM', 'Country': 'Somalia', 'Female': 5, 'Male': 1, 'Total athletes': 6},
    {'Country_Code': 'DJI', 'Country': 'Djibouti', 'Female': 1, 'Male': 5, 'Total athletes': 6},
    {'Country_Code': 'GAB', 'Country': 'Gabon', 'Female': 1, 'Male': 5, 'Total athletes': 6},
    {'Country_Code': 'COD', 'Country': 'Democratic Republic of the Congo', 'Female': 1, 'Male': 4, 'Total athletes': 5},
    {'Country_Code': 'TLS', 'Country': 'Timor-Leste', 'Female': 2, 'Male': 3, 'Total athletes': 5},
    {'Country_Code': 'SEY', 'Country': 'Seychelles', 'Female': 3, 'Male': 2, 'Total athletes': 5},
    {'Country_Code': 'CGO', 'Country': 'Congo', 'Female': 3, 'Male': 2, 'Total athletes': 5},
    {'Country_Code': 'MDV', 'Country': 'Maldives', 'Female': 4, 'Male': 0, 'Total athletes': 4},
    {'Country_Code': 'SMR', 'Country': 'San Marino', 'Female': 2, 'Male': 2, 'Total athletes': 4},
    {'Country_Code': 'BIZ', 'Country': 'Belize', 'Female': 3, 'Male': 1, 'Total athletes': 4},
    {'Country_Code': 'HAI', 'Country': 'Haiti', 'Female': 2, 'Male': 2, 'Total athletes': 4},
    {'Country_Code': 'NCA', 'Country': 'Nicaragua', 'Female': 2, 'Male': 1, 'Total athletes': 3},
    {'Country_Code': 'KIR', 'Country': 'Kiribati', 'Female': 1, 'Male': 2, 'Total athletes': 3},
    {'Country_Code': 'SWZ', 'Country': 'Eswatini', 'Female': 2, 'Male': 1, 'Total athletes': 3},
    {'Country_Code': 'BRU', 'Country': 'Brunei Darussalam', 'Female': 1, 'Male': 2, 'Total athletes': 3},
    {'Country_Code': 'CHA', 'Country': 'Chad', 'Female': 1, 'Male': 2, 'Total athletes': 3},
    {'Country_Code': 'LAO', 'Country': 'Lao People\'s Democratic Republic', 'Female': 1, 'Male': 2, 'Total athletes': 3},
    {'Country_Code': 'MAL', 'Country': 'Malta', 'Female': 1, 'Male': 2, 'Total athletes': 3},
    {'Country_Code': 'ISL', 'Country': 'Iceland', 'Female': 2, 'Male': 0, 'Total athletes': 2},
    {'Country_Code': 'STP', 'Country': 'Sao Tome and Principe', 'Female': 1, 'Male': 1, 'Total athletes': 2},
    {'Country_Code': 'CAM', 'Country': 'Cambodia', 'Female': 1, 'Male': 1, 'Total athletes': 2},
    {'Country_Code': 'YEM', 'Country': 'Yemen', 'Female': 1, 'Male': 1, 'Total athletes': 2},
    {'Country_Code': 'AND', 'Country': 'Andorra', 'Female': 0, 'Male': 2, 'Total athletes': 2},
    {'Country_Code': 'BER', 'Country': 'Bermuda', 'Female': 0, 'Male': 2, 'Total athletes': 2},
    {'Country_Code': 'SOL', 'Country': 'Solomon Islands', 'Female': 1, 'Male': 0, 'Total athletes': 1},
    {'Country_Code': 'LBR', 'Country': 'Liberia', 'Female': 1, 'Male': 0, 'Total athletes': 1},
    {'Country_Code': 'TUV', 'Country': 'Tuvalu', 'Female': 1, 'Male': 0, 'Total athletes': 1},
    {'Country_Code': 'RWA', 'Country': 'Rwanda', 'Female': 1, 'Male': 0, 'Total athletes': 1},
    {'Country_Code': 'STK', 'Country': 'St Kitts and Nevis', 'Female': 0, 'Male': 1, 'Total athletes': 1},
    {'Country_Code': 'MON', 'Country': 'Monaco', 'Female': 0, 'Male': 1, 'Total athletes': 1},
    {'Country_Code': 'CUW', 'Country': 'Curaçao', 'Female': 0, 'Male': 1, 'Total athletes': 1},
    {'Country_Code': 'SUR', 'Country': 'Suriname', 'Female': 2, 'Male': 6, 'Total athletes': 8},
    {'Country_Code': 'LBR', 'Country': 'Liberia', 'Female': 1, 'Male': 0, 'Total athletes': 1},
    {'Country_Code': 'LBA', 'Country': 'Libya', 'Female': 1, 'Male': 3, 'Total Athletes': 4},
    {'Country_Code': 'MYA', 'Country': 'Myanmar', 'Female': 0, 'Male': 3, 'Total Athletes': 3},
    {'Country_Code': 'YEM', 'Country': 'Yemen', 'Female': 1, 'Male': 1, 'Total Athletes': 2},
    {'Country_Code': 'SOM', 'Country': 'Somalia', 'Female': 1, 'Male': 1, 'Total Athletes': 2},
    {'Country_Code': 'COM', 'Country': 'Comoros', 'Female': 1, 'Male': 1, 'Total Athletes': 2},
    {'Country_Code': 'CAF', 'Country': 'Central African Republic', 'Female': 0, 'Male': 2, 'Total Athletes': 2},
    {'Country_Code': 'GAB', 'Country': 'Gabon', 'Female': 0, 'Male': 2, 'Total Athletes': 2},
    {'Country_Code': 'NEP', 'Country': 'Nepal', 'Female': 1, 'Male': 1, 'Total Athletes': 2},
    {'Country_Code': 'SLE', 'Country': 'Sierra Leone', 'Female': 1, 'Male': 1, 'Total Athletes': 2},
    {'Country_Code': 'MAD', 'Country': 'Madagascar', 'Female': 0, 'Male': 2, 'Total Athletes': 2},
    {'Country_Code': 'CHA', 'Country': 'Chad', 'Female': 1, 'Male': 1, 'Total Athletes': 2},
    {'Country_Code': 'LES', 'Country': 'Lesotho', 'Female': 1, 'Male': 1, 'Total Athletes': 2},
    {'Country_Code': 'MTN', 'Country': 'Mauritania', 'Female': 0, 'Male': 2, 'Total Athletes': 2},
    {'Country_Code': 'STP', 'Country': 'Sao Tome and Principe', 'Female': 1, 'Male': 1, 'Total Athletes': 2},
    {'Country_Code': 'SWZ', 'Country': 'Eswatini', 'Female': 1, 'Male': 1, 'Total Athletes': 2},
    {'Country_Code': 'BEN', 'Country': 'Benin', 'Female': 1, 'Male': 1, 'Total Athletes': 2},
    {'Country_Code': 'NAM', 'Country': 'Namibia', 'Female': 2, 'Male': 0, 'Total Athletes': 2},
    {'Country_Code': 'FSM', 'Country': 'Micronesia', 'Female': 1, 'Male': 1, 'Total Athletes': 2},
    {'Country_Code': 'GAM', 'Country': 'Gambia', 'Female': 1, 'Male': 1, 'Total Athletes': 2},
    {'Country_Code': 'AND', 'Country': 'Andorra', 'Female': 1, 'Male': 0, 'Total Athletes': 1},
    {'Country_Code': 'PLW', 'Country': 'Palau', 'Female': 1, 'Male': 0, 'Total Athletes': 1},
    {'Country_Code': 'TLS', 'Country': 'Timor-Leste', 'Female': 1, 'Male': 0, 'Total Athletes': 1},
    {'Country_Code': 'SOL', 'Country': 'Solomon Islands', 'Female': 1, 'Male': 0, 'Total Athletes': 1},
    {'Country_Code': 'SSD', 'Country': 'South Sudan', 'Female': 1, 'Male': 0, 'Total Athletes': 1},
    {'Country_Code': 'TGA', 'Country': 'Tonga', 'Female': 0, 'Male': 1, 'Total Athletes': 1},
    {'Country_Code': 'COK', 'Country': 'Cook Islands', 'Female': 1, 'Male': 0, 'Total Athletes': 1},
    {'Country_Code': 'MTQ', 'Country': 'Martinique', 'Female': 1, 'Male': 0, 'Total Athletes': 1},
    {'Country_Code': 'NRU', 'Country': 'Nauru', 'Female': 0, 'Male': 1, 'Total Athletes': 1},
    {'Country_Code': 'VIN', 'Country': 'Saint Vincent and the Grenadines', 'Female': 1, 'Male': 0, 'Total Athletes': 1},
    {'Country_Code': 'TUV', 'Country': 'Tuvalu', 'Female': 0, 'Male': 1, 'Total Athletes': 1},
    {'Country_Code': 'VAN', 'Country': 'Vanuatu', 'Female': 0, 'Male': 1, 'Total Athletes': 1},
    {'Country_Code': 'SMR', 'Country': 'San Marino', 'Female': 0, 'Male': 1, 'Total Athletes': 1},
    {'Country_Code': 'GRN', 'Country': 'Grenada', 'Female': 0, 'Male': 1, 'Total Athletes': 1},
    {'Country_Code': 'DJI', 'Country': 'Djibouti', 'Female': 0, 'Male': 1, 'Total Athletes': 1},
    {'Country_Code': 'MHL', 'Country': 'Marshall Islands', 'Female': 0, 'Male': 1, 'Total Athletes': 1},
    {'Country_Code': 'DMA', 'Country': 'Dominica', 'Female': 0, 'Male': 1, 'Total Athletes': 1},
    {'Country_Code': 'MON', 'Country': 'Monaco', 'Female': 0, 'Male': 1, 'Total Athletes': 1},
    {'Country_Code': 'NRU', 'Country': 'Nauru', 'Female': 0, 'Male': 1, 'Total Athletes': 1},
    {'Country_Code': 'NCA', 'Country': 'Nicaragua', 'Female': 0, 'Male': 1, 'Total Athletes': 1},
    {'Country_Code': 'MAW', 'Country': 'Malawi', 'Female': 0, 'Male': 1, 'Total Athletes': 1}

]

def print_simple_table(data):
    # Print the header
    print("Country                   | Female  | Male   | Total  ")
    print("--------------------------|---------|--------|--------")

    # Print each row
    for entry in data:
        print(f"{entry['Country']:25} | {entry['Female']:7} | {entry['Male']:7} | {entry['Total']:7}")

# Call the function to print the table
print_simple_table(athletes_list)
