athletes_list = [
    {'Country': 'United States', 'Female': 328, 'Male': 291, 'Total': 619},
    {'Country': 'France', 'Female': 295, 'Male': 305, 'Total': 600},
    {'Country': 'Australia', 'Female': 265, 'Male': 210, 'Total': 475},
    {'Country': 'Germany', 'Female': 225, 'Male': 232, 'Total': 457},
    {'Country': 'Japan', 'Female': 201, 'Male': 230, 'Total': 431},
    {'Country': 'Spain', 'Female': 202, 'Male': 199, 'Total': 401},
    {'Country': 'China', 'Female': 264, 'Male': 134, 'Total': 398},
    {'Country': 'Italy', 'Female': 192, 'Male': 205, 'Total': 397},
    {'Country': 'Great Britain', 'Female': 178, 'Male': 164, 'Total': 342},
    {'Country': 'Canada', 'Female': 203, 'Male': 129, 'Total': 332},
    {'Country': 'Brazil', 'Female': 164, 'Male': 126, 'Total': 290},
    {'Country': 'Netherlands', 'Female': 172, 'Male': 117, 'Total': 289},
    {'Country': 'Poland', 'Female': 124, 'Male': 102, 'Total': 226},
    {'Country': 'New Zealand', 'Female': 101, 'Male': 107, 'Total': 208},
    {'Country': 'Hungary', 'Female': 85, 'Male': 92, 'Total': 177},
    {'Country': 'Belgium', 'Female': 88, 'Male': 89, 'Total': 177},
    {'Country': 'Egypt', 'Female': 54, 'Male': 103, 'Total': 157},
    {'Country': 'Korea', 'Female': 81, 'Male': 66, 'Total': 147},
    {'Country': 'Ireland', 'Female': 69, 'Male': 74, 'Total': 143},
    {'Country': 'Argentina', 'Female': 33, 'Male': 110, 'Total': 143},
    {'Country': 'South Africa', 'Female': 63, 'Male': 78, 'Total': 141},
    {'Country': 'Ukraine', 'Female': 69, 'Male': 72, 'Total': 141},
    {'Country': 'Switzerland', 'Female': 66, 'Male': 71, 'Total': 137},
    {'Country': 'Denmark', 'Female': 74, 'Male': 57, 'Total': 131},
    {'Country': 'Sweden', 'Female': 66, 'Male': 59, 'Total': 125},
    {'Country': 'Serbia', 'Female': 44, 'Male': 70, 'Total': 114},
    {'Country': 'India', 'Female': 46, 'Male': 66, 'Total': 112},
    {'Country': 'Czechia', 'Female': 49, 'Male': 62, 'Total': 111},
    {'Country': 'Norway', 'Female': 53, 'Male': 56, 'Total': 109},
    {'Country': 'Mexico', 'Female': 63, 'Male': 45, 'Total': 108},
    {'Country': 'Türkiye', 'Female': 54, 'Male': 47, 'Total': 101},
    {'Country': 'Greece', 'Female': 41, 'Male': 59, 'Total': 100},
    {'Country': 'Romania', 'Female': 47, 'Male': 49, 'Total': 96},
    {'Country': 'Slovenia', 'Female': 47, 'Male': 48, 'Total': 95},
    {'Country': 'Israel', 'Female': 33, 'Male': 56, 'Total': 89},
    {'Country': 'Colombia', 'Female': 51, 'Male': 37, 'Total': 88},
    {'Country': 'Uzbekistan', 'Female': 31, 'Male': 57, 'Total': 88},
    {'Country': 'Nigeria', 'Female': 63, 'Male': 23, 'Total': 86},
    {'Country': 'Austria', 'Female': 37, 'Male': 47, 'Total': 84},
    {'Country': 'Kazakhstan', 'Female': 25, 'Male': 54, 'Total': 79},
    {'Country': 'Portugal', 'Female': 37, 'Male': 38, 'Total': 75},
    {'Country': 'Kenya', 'Female': 34, 'Male': 40, 'Total': 74},
    {'Country': 'Croatia', 'Female': 15, 'Male': 58, 'Total': 73},
    {'Country': 'Jamaica', 'Female': 32, 'Male': 33, 'Total': 65},
    {'Country': 'Morocco', 'Female': 18, 'Male': 43, 'Total': 61},
    {'Country': 'Cuba', 'Female': 27, 'Male': 34, 'Total': 61},
    {'Country': 'Chinese Taipei', 'Female': 34, 'Male': 26, 'Total': 60},
    {'Country': 'Dominican Republic', 'Female': 25, 'Male': 34, 'Total': 59},
    {'Country': 'Finland', 'Female': 34, 'Male': 23, 'Total': 57},
    {'Country': 'Thailand', 'Female': 28, 'Male': 24, 'Total': 52},
    {'Country': 'Lithuania', 'Female': 24, 'Male': 27, 'Total': 51},
    {'Country': 'Puerto Rico', 'Female': 24, 'Male': 27, 'Total': 51},
    {'Country': 'Azerbaijan', 'Female': 20, 'Male': 28, 'Total': 48},
    {'Country': 'Chile', 'Female': 18, 'Male': 30, 'Total': 48},
    {'Country': 'Bulgaria', 'Female': 25, 'Male': 21, 'Total': 46},
    {'Country': 'Algeria', 'Female': 19, 'Male': 27, 'Total': 46},
    {'Country': 'IR Iran', 'Female': 11, 'Male': 30, 'Total': 41},
    {'Country': 'Ecuador', 'Female': 24, 'Male': 16, 'Total': 40},
    {'Country': 'EOR', 'Female': 13, 'Male': 24, 'Total': 37},
    {'Country': 'Fiji', 'Female': 17, 'Male': 19, 'Total': 36},
    {'Country': 'Hong Kong, China', 'Female': 18, 'Male': 16, 'Total': 34},
    {'Country': 'Ethiopia', 'Female': 17, 'Male': 16, 'Total': 33},
    {'Country': 'AIN', 'Female': 17, 'Male': 15, 'Total': 32},
    {'Country': 'Mongolia', 'Female': 18, 'Male': 14, 'Total': 32},
    {'Country': 'Zambia', 'Female': 22, 'Male': 9, 'Total': 31},
    {'Country': 'Venezuela', 'Female': 14, 'Male': 17, 'Total': 31},
    {'Country': 'Paraguay', 'Female': 6, 'Male': 23, 'Total': 29},
    {'Country': 'Indonesia', 'Female': 13, 'Male': 16, 'Total': 29},
    {'Country': 'Latvia', 'Female': 13, 'Male': 16, 'Total': 29},
    {'Country': 'Slovakia', 'Female': 14, 'Male': 14, 'Total': 28},
    {'Country': 'Georgia', 'Female': 7, 'Male': 21, 'Total': 28},
    {'Country': 'Uruguay', 'Female': 4, 'Male': 23, 'Total': 27},
    {'Country': 'Malaysia', 'Female': 13, 'Male': 13, 'Total': 26},
    {'Country': 'Tunisia', 'Female': 14, 'Male': 12, 'Total': 26},
    {'Country': 'Peru', 'Female': 17, 'Male': 9, 'Total': 26},
    {'Country': 'Republic of Moldova', 'Female': 12, 'Male': 14, 'Total': 26},
    {'Country': 'Guinea', 'Female': 5, 'Male': 20, 'Total': 25}
]

def print_simple_table(data):
    # Print the header
    print("Country                   | Female  | Male   | Total  ")
    print("--------------------------|---------|--------|--------")

    # Print each row
    for entry in data:
        print(f"{entry['Country']:25} | {entry['Female']:7} | {entry['Male']:7} | {entry['Total']:7}")

# Call the function to print the table
print_simple_table(athletes_list)
