athletes_data = {
    'United States': {'Female': 328, 'Male': 291, 'Total': 619},
    'France': {'Female': 295, 'Male': 305, 'Total': 600},
    'Australia': {'Female': 265, 'Male': 210, 'Total': 475},
    'Germany': {'Female': 225, 'Male': 232, 'Total': 457},
    'Japan': {'Female': 201, 'Male': 230, 'Total': 431},
    'Spain': {'Female': 202, 'Male': 199, 'Total': 401},
    'China': {'Female': 264, 'Male': 134, 'Total': 398},
    'Italy': {'Female': 192, 'Male': 205, 'Total': 397},
    'Great Britain': {'Female': 178, 'Male': 164, 'Total': 342},
    'Canada': {'Female': 203, 'Male': 129, 'Total': 332},
    'Brazil': {'Female': 164, 'Male': 126, 'Total': 290},
    'Netherlands': {'Female': 172, 'Male': 117, 'Total': 289},
    'Poland': {'Female': 124, 'Male': 102, 'Total': 226},
    'New Zealand': {'Female': 101, 'Male': 107, 'Total': 208},
    'Hungary': {'Female': 85, 'Male': 92, 'Total': 177},
    'Belgium': {'Female': 88, 'Male': 89, 'Total': 177},
    'Egypt': {'Female': 54, 'Male': 103, 'Total': 157},
    'Korea': {'Female': 81, 'Male': 66, 'Total': 147},
    'Ireland': {'Female': 69, 'Male': 74, 'Total': 143},
    'Argentina': {'Female': 33, 'Male': 110, 'Total': 143},
    'South Africa': {'Female': 63, 'Male': 78, 'Total': 141},
    'Ukraine': {'Female': 69, 'Male': 72, 'Total': 141},
    'Switzerland': {'Female': 66, 'Male': 71, 'Total': 137},
    'Denmark': {'Female': 74, 'Male': 57, 'Total': 131},
    'Sweden': {'Female': 66, 'Male': 59, 'Total': 125},
    'Serbia': {'Female': 44, 'Male': 70, 'Total': 114},
    'India': {'Female': 46, 'Male': 66, 'Total': 112},
    'Czechia': {'Female': 49, 'Male': 62, 'Total': 111},
    'Norway': {'Female': 53, 'Male': 56, 'Total': 109},
    'Mexico': {'Female': 63, 'Male': 45, 'Total': 108},
    'Türkiye': {'Female': 54, 'Male': 47, 'Total': 101},
    'Greece': {'Female': 41, 'Male': 59, 'Total': 100},
    'Romania': {'Female': 47, 'Male': 49, 'Total': 96},
    'Slovenia': {'Female': 47, 'Male': 48, 'Total': 95},
    'Israel': {'Female': 33, 'Male': 56, 'Total': 89},
    'Colombia': {'Female': 51, 'Male': 37, 'Total': 88},
    'Uzbekistan': {'Female': 31, 'Male': 57, 'Total': 88},
    'Nigeria': {'Female': 63, 'Male': 23, 'Total': 86},
    'Austria': {'Female': 37, 'Male': 47, 'Total': 84},
    'Kazakhstan': {'Female': 25, 'Male': 54, 'Total': 79},
    'Portugal': {'Female': 37, 'Male': 38, 'Total': 75},
    'Kenya': {'Female': 34, 'Male': 40, 'Total': 74},
    'Croatia': {'Female': 15, 'Male': 58, 'Total': 73},
    'Jamaica': {'Female': 32, 'Male': 33, 'Total': 65},
    'Morocco': {'Female': 18, 'Male': 43, 'Total': 61},
    'Cuba': {'Female': 27, 'Male': 34, 'Total': 61},
    'Chinese Taipei': {'Female': 34, 'Male': 26, 'Total': 60},
    'Dominican Republic': {'Female': 25, 'Male': 34, 'Total': 59},
    'Finland': {'Female': 34, 'Male': 23, 'Total': 57},
    'Thailand': {'Female': 28, 'Male': 24, 'Total': 52},
    'Lithuania': {'Female': 24, 'Male': 27, 'Total': 51},
    'Puerto Rico': {'Female': 24, 'Male': 27, 'Total': 51},
    'Azerbaijan': {'Female': 20, 'Male': 28, 'Total': 48},
    'Chile': {'Female': 18, 'Male': 30, 'Total': 48},
    'Bulgaria': {'Female': 25, 'Male': 21, 'Total': 46},
    'Algeria': {'Female': 19, 'Male': 27, 'Total': 46},
    'IR Iran': {'Female': 11, 'Male': 30, 'Total': 41},
    'Ecuador': {'Female': 24, 'Male': 16, 'Total': 40},
    'EOR': {'Female': 13, 'Male': 24, 'Total': 37},
    'Fiji': {'Female': 17, 'Male': 19, 'Total': 36},
    'Hong Kong, China': {'Female': 18, 'Male': 16, 'Total': 34},
    'Ethiopia': {'Female': 17, 'Male': 16, 'Total': 33},
    'AIN': {'Female': 17, 'Male': 15, 'Total': 32},
    'Mongolia': {'Female': 18, 'Male': 14, 'Total': 32},
    'Zambia': {'Female': 22, 'Male': 9, 'Total': 31},
    'Venezuela': {'Female': 14, 'Male': 17, 'Total': 31},
    'Paraguay': {'Female': 6, 'Male': 23, 'Total': 29},
    'Indonesia': {'Female': 13, 'Male': 16, 'Total': 29},
    'Latvia': {'Female': 13, 'Male': 16, 'Total': 29},
    'Slovakia': {'Female': 14, 'Male': 14, 'Total': 28},
    'Georgia': {'Female': 7, 'Male': 21, 'Total': 28},
    'Uruguay': {'Female': 4, 'Male': 23, 'Total': 27},
    'Malaysia': {'Female': 13, 'Male': 13, 'Total': 26},
    'Tunisia': {'Female': 14, 'Male': 12, 'Total': 26},
    'Peru': {'Female': 17, 'Male': 9, 'Total': 26},
    'Republic of Moldova': {'Female': 12, 'Male': 14, 'Total': 26},
    'Guinea': {'Female': 5, 'Male': 20, 'Total': 25},
    'Uganda': {'Female': 13, 'Male': 12, 'Total': 25},
    'Angola': {'Female': 17, 'Male': 8, 'Total': 25},
    'Samoa': {'Female': 4, 'Male': 20, 'Total': 24},
    'Mali': {'Female': 2, 'Male': 22, 'Total': 24},
    'Estonia': {'Female': 8, 'Male': 16, 'Total': 24},
    'Singapore': {'Female': 16, 'Male': 7, 'Total': 23},
    'Iraq': {'Female': 0, 'Male': 23, 'Total': 23},
    'Philippines': {'Female': 15, 'Male': 7, 'Total': 22},
    'Bahamas': {'Female': 8, 'Male': 11, 'Total': 19},
    'Montenegro': {'Female': 3, 'Male': 16, 'Total': 19},
    'Trinidad and Tobago': {'Female': 7, 'Male': 10, 'Total': 17},
    'Vietnam': {'Female': 10, 'Male': 7, 'Total': 17},
    'Barbados': {'Female': 7, 'Male': 10, 'Total': 17},
    'Qatar': {'Female': 2, 'Male': 14, 'Total': 16},
    'Mozambique': {'Female': 4, 'Male': 12, 'Total': 16},
    'Democratic Republic of the Congo': {'Female': 3, 'Male': 12, 'Total': 15},
    'Sudan': {'Female': 3, 'Male': 12, 'Total': 15},
    'Kyrgyzstan': {'Female': 6, 'Male': 8, 'Total': 14},
    'El Salvador': {'Female': 3, 'Male': 11, 'Total': 14},
    'Sri Lanka': {'Female': 8, 'Male': 6, 'Total': 14},
    'Afghanistan': {'Female': 1, 'Male': 13, 'Total': 14},
    'North Macedonia': {'Female': 4, 'Male': 9, 'Total': 13},
    'Luxembourg': {'Female': 4, 'Male': 8, 'Total': 12},
    'Lebanon': {'Female': 2, 'Male': 10, 'Total': 12},
    'Jordan': {'Female': 3, 'Male': 8, 'Total': 11},
    'Gabon': {'Female': 4, 'Male': 6, 'Total': 10},
    'Namibia': {'Female': 6, 'Male': 3, 'Total': 9},
    'Kuwait': {'Female': 2, 'Male': 7, 'Total': 9},
    'Botswana': {'Female': 4, 'Male': 4, 'Total': 8},
    'Malta': {'Female': 4, 'Male': 4, 'Total': 8},
    'Turkmenistan': {'Female': 2, 'Male': 6, 'Total': 8},
    'Guatemala': {'Female': 2, 'Male': 6, 'Total': 8},
    'Syria': {'Female': 1, 'Male': 7, 'Total': 8},
    'Albania': {'Female': 2, 'Male': 6, 'Total': 8},
    'Niger': {'Female': 1, 'Male': 6, 'Total': 7},
    'Grenada': {'Female': 1, 'Male': 6, 'Total': 7},
    'Papua New Guinea': {'Female': 3, 'Male': 4, 'Total': 7},
    'Madagascar': {'Female': 4, 'Male': 3, 'Total': 7},
    'Kosovo': {'Female': 5, 'Male': 1, 'Total': 6},
    'Somalia': {'Female': 3, 'Male': 3, 'Total': 6},
    'Gambia': {'Female': 2, 'Male': 4, 'Total': 6},
    'Malawi': {'Female': 4, 'Male': 2, 'Total': 6},
    'Guyana': {'Female': 1, 'Male': 4, 'Total': 5},
    'Dominica': {'Female': 2, 'Male': 3, 'Total': 5},
    'Cayman Islands': {'Female': 1, 'Male': 4, 'Total': 5},
    'Andorra': {'Female': 0, 'Male': 4, 'Total': 4},
    'Liberia': {'Female': 2, 'Male': 2, 'Total': 4},
    'Brunei Darussalam': {'Female': 0, 'Male': 3, 'Total': 3},
    'Nauru': {'Female': 0, 'Male': 3, 'Total': 3},
    'Saint Kitts and Nevis': {'Female': 1, 'Male': 2, 'Total': 3},
    'Saint Vincent and the Grenadines': {'Female': 0, 'Male': 3, 'Total': 3},
    'Sao Tome and Principe': {'Female': 0, 'Male': 3, 'Total': 3},
    'Lesotho': {'Female': 2, 'Male': 1, 'Total': 3},
    'Chad': {'Female': 2, 'Male': 1, 'Total': 3},
    'Palau': {'Female': 1, 'Male': 2, 'Total': 3},
    'Bhutan': {'Female': 0, 'Male': 2, 'Total': 2},
    'Montserrat': {'Female': 0, 'Male': 2, 'Total': 2},
    'Central African Republic': {'Female': 0, 'Male': 2, 'Total': 2},
    'Vanuatu': {'Female': 1, 'Male': 1, 'Total': 2},
    'Togo': {'Female': 1, 'Male': 1, 'Total': 2},
    'Swaziland': {'Female': 1, 'Male': 1, 'Total': 2},
    'Seychelles': {'Female': 1, 'Male': 1, 'Total': 2},
    'Tuvalu': {'Female': 0, 'Male': 1, 'Total': 1},
    'Solomon Islands': {'Female': 0, 'Male': 1, 'Total': 1},
    'Libya': {'Female': 0, 'Male': 1, 'Total': 1},
    'Saint Lucia': {'Female': 1, 'Male': 0, 'Total': 1},
    'Honduras': {'Female': 0, 'Male': 1, 'Total': 1},
    'Guam': {'Female': 0, 'Male': 1, 'Total': 1},
    'Comoros': {'Female': 0, 'Male': 1, 'Total': 1}
}
def Total_Athletes(athletes_data):
    total_female = 0
    total_male = 0
    total_athletes = 0
    for country, data in athletes_data.items():
        total_female += data['Female']
        total_male += data['Male']
        total_athletes += data['Total']
    #Total
    print("Total Female Athletes:", total_female)
    print("Total Male Athletes:", total_male)
    print("Total Athletes:", total_athletes)
    # return athletes_data
Total_Athletes(athletes_data)
